import { Component, Input, OnInit} from '@angular/core';
import { Rider, Horse } from '../../../models';

@Component({
  selector: 'sn-riderlist-rider',
  templateUrl: './rider.component.html',
  styleUrls: ['./rider.component.scss']
})
export class RiderlistRiderComponent implements OnInit {
  @Input() rider: Rider;
  horsesShow: Horse[];

  ngOnInit() {
    this.horsesShow = this.rider.horses.sort((a, b) => { if (this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return -1; } else if (this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return 1; } if (this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return -1; } else if (this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return 1; } return 0; });
    // this.horsesShow = this.rider.horses.filter(h => h.scores.some(s => s.Horse.Fei === h.Fei && s.Rider.Fei === this.rider.Fei && s.Competition.Fei === '2019_LEXINGTON')).sort((a, b) => { if (this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return -1; } else if (this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return 1; } if (this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return -1; } else if (this.rider.scores.filter(s => s.Horse.Fei === b.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei > this.rider.scores.filter(s => s.Horse.Fei === a.Fei).sort((x, y) => { if (x.Competition.Fei > y.Competition.Fei) { return -1; } else if (y.Competition.Fei > x.Competition.Fei) { return 1; } return 0; })[0].Competition.Fei) { return 1; } return 0; });
    // this.horsesShow = this.rider.horses.filter(h => h.Fei === '104BY63');
  }
}

