export enum Studbook {
    AA = 'Anglo Arab',
    AES = 'Anglo-European',
    BB = 'Brandenburger',
    BWBS = 'British Warmblood',
    BWP = 'Belgian Warmblood',
    DSP = 'German Warmblood',
    FR = 'Selle Francais',
    HAN = 'Hanoverian',
    HOL = 'Holsteiner',
    ISH = 'Irish Sport Horse',
    KWPN = 'Dutch Warmblood',
    MB = 'Mecklenburger',
    NTR = 'Non-Thoroughbred Register',
    O = 'Oldenburg',
    SHBGB = 'British Sport Horse',
    TB = 'Thoroughbred',
    TRK = 'Trakehner',
    W = 'Westfalian'
}
